spring:
  jackson.serialization.indent_output: ${JACKSON_INDENT_OUTPUT:true}
  h2.console.enabled: ${H2_CONSOLE_ENABLED:false}
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate.ddl-auto: ${DDL_AUTO:update}
